name: Deploy to EKS

on:
  workflow_dispatch:    # Allows manual triggering

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update kubeconfig
        run: aws eks --region us-east-1 update-kubeconfig --name EKS_CLOUD

      - name: Deploy to EKS
        run: kubectl delete -f deployment-service.yml
